#!/bin/bash

echo Updating the JNI files...

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )


eval cd ${DIR}/../
export NDK_PROJECT_PATH=.
rm -Rf libs/ obj/
ndk-build NDK_APPLICATION_MK=./jni/Android.mk

echo Done
